export const INITIAL_Data = {
  location: {
    name: "Delhi",
    region: "Delhi",
    country: "India",
    lat: 28.667,
    lon: 77.217,
    tz_id: "Asia/Kolkata",
    localtime_epoch: 1728195276,
    localtime: "2024-10-06 11:44",
  },
  current: {
    last_updated_epoch: 1728194400,
    last_updated: "2024-10-06 11:30",
    temp_c: 33.2,
    temp_f: 91.8,
    is_day: 1,
    condition: {
      text: "Mist",
      icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
      code: 1030,
    },
    wind_mph: 6,
    wind_kph: 9.7,
    wind_degree: 330,
    wind_dir: "NNW",
    pressure_mb: 1014,
    pressure_in: 29.94,
    precip_mm: 0,
    precip_in: 0,
    humidity: 44,
    cloud: 0,
    feelslike_c: 32.6,
    feelslike_f: 90.6,
    windchill_c: 34.4,
    windchill_f: 93.9,
    heatindex_c: 34.2,
    heatindex_f: 93.6,
    dewpoint_c: 13.8,
    dewpoint_f: 56.8,
    vis_km: 4.5,
    vis_miles: 2,
    uv: 8,
    gust_mph: 7,
    gust_kph: 11.2,
  },
  forecast: {
    forecastday: [
      {
        date: "2024-10-06",
        date_epoch: 1728172800,
        day: {
          maxtemp_c: 36,
          maxtemp_f: 96.9,
          mintemp_c: 28.1,
          mintemp_f: 82.6,
          avgtemp_c: 31.9,
          avgtemp_f: 89.5,
          maxwind_mph: 9.4,
          maxwind_kph: 15.1,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 37,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 7,
        },
      },
      {
        date: "2024-10-07",
        date_epoch: 1728259200,
        day: {
          maxtemp_c: 36.8,
          maxtemp_f: 98.3,
          mintemp_c: 28.4,
          mintemp_f: 83.1,
          avgtemp_c: 32.1,
          avgtemp_f: 89.9,
          maxwind_mph: 7.2,
          maxwind_kph: 11.5,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 40,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 6,
        },
      },
      {
        date: "2024-10-08",
        date_epoch: 1728345600,
        day: {
          maxtemp_c: 36.2,
          maxtemp_f: 97.2,
          mintemp_c: 28,
          mintemp_f: 82.4,
          avgtemp_c: 31.8,
          avgtemp_f: 89.3,
          maxwind_mph: 6.3,
          maxwind_kph: 10.1,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          totalsnow_cm: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 43,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 7,
        },
      },
    ],
  },
};
